//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.xepher.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.xepher.lang.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换.
        /// </summary>
        public static string ApplicationBarIconButtonDirection {
            get {
                return ResourceManager.GetString("ApplicationBarIconButtonDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string ApplicationBarIconButtonRefresh {
            get {
                return ResourceManager.GetString("ApplicationBarIconButtonRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string ApplicationBarIconButtonSearch {
            get {
                return ResourceManager.GetString("ApplicationBarIconButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string ApplicationBarMenuItemAbout {
            get {
                return ResourceManager.GetString("ApplicationBarMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string ApplicationBarMenuItemSettings {
            get {
                return ResourceManager.GetString("ApplicationBarMenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无锡公交查询(WP).
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者 : xepher.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定退出程序吗？.
        /// </summary>
        public static string MsgExitApplication {
            get {
                return ResourceManager.GetString("MsgExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无网络连接！请确认网络连接后重启客户端！.
        /// </summary>
        public static string MsgNetworkUnavailable {
            get {
                return ResourceManager.GetString("MsgNetworkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定刷新线路吗？.
        /// </summary>
        public static string MsgRefreshRoutes {
            get {
                return ResourceManager.GetString("MsgRefreshRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定刷新 {0} 吗？.
        /// </summary>
        public static string MsgRefreshStations {
            get {
                return ResourceManager.GetString("MsgRefreshStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你当前选中的线路还没有被缓存过，请按刷新按钮来获取令牌然后再查询该线路信息。.
        /// </summary>
        public static string MsgRefreshToken {
            get {
                return ResourceManager.GetString("MsgRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string PageAbout {
            get {
                return ResourceManager.GetString("PageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车辆.
        /// </summary>
        public static string PageBusses {
            get {
                return ResourceManager.GetString("PageBusses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线路.
        /// </summary>
        public static string PageMain {
            get {
                return ResourceManager.GetString("PageMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string PageSearch {
            get {
                return ResourceManager.GetString("PageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 站台.
        /// </summary>
        public static string PageStations {
            get {
                return ResourceManager.GetString("PageStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网络 : .
        /// </summary>
        public static string SettingsNetwork {
            get {
                return ResourceManager.GetString("SettingsNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中国移动.
        /// </summary>
        public static string SettingsNetworkMobile {
            get {
                return ResourceManager.GetString("SettingsNetworkMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中国电信.
        /// </summary>
        public static string SettingsNetworkTelecom {
            get {
                return ResourceManager.GetString("SettingsNetworkTelecom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中国联通.
        /// </summary>
        public static string SettingsNetworkUnicom {
            get {
                return ResourceManager.GetString("SettingsNetworkUnicom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载中....
        /// </summary>
        public static string SystemTrayLoadingText {
            get {
                return ResourceManager.GetString("SystemTrayLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出程序.
        /// </summary>
        public static string TitleExitApplication {
            get {
                return ResourceManager.GetString("TitleExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新线路.
        /// </summary>
        public static string TitleRefreshRoutes {
            get {
                return ResourceManager.GetString("TitleRefreshRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新站台.
        /// </summary>
        public static string TitleRefreshStations {
            get {
                return ResourceManager.GetString("TitleRefreshStations", resourceCulture);
            }
        }
    }
}
