//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace org.xepher.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("org.xepher.lang.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加附近站台图层.
        /// </summary>
        public static string ApplicationBarIconButtonAddStationsTile {
            get {
                return ResourceManager.GetString("ApplicationBarIconButtonAddStationsTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 换乘.
        /// </summary>
        public static string ApplicationBarIconButtonChange {
            get {
                return ResourceManager.GetString("ApplicationBarIconButtonChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换.
        /// </summary>
        public static string ApplicationBarIconButtonDirection {
            get {
                return ResourceManager.GetString("ApplicationBarIconButtonDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定位.
        /// </summary>
        public static string ApplicationBarIconButtonLocate {
            get {
                return ResourceManager.GetString("ApplicationBarIconButtonLocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除图层.
        /// </summary>
        public static string ApplicationBarIconButtonMinusTile {
            get {
                return ResourceManager.GetString("ApplicationBarIconButtonMinusTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string ApplicationBarIconButtonSearch {
            get {
                return ResourceManager.GetString("ApplicationBarIconButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 切换引擎.
        /// </summary>
        public static string ApplicationBarIconButtonSwichRoadTile {
            get {
                return ResourceManager.GetString("ApplicationBarIconButtonSwichRoadTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string ApplicationBarMenuItemAbout {
            get {
                return ResourceManager.GetString("ApplicationBarMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string ApplicationBarMenuItemSettings {
            get {
                return ResourceManager.GetString("ApplicationBarMenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无锡公交(WP).
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xepher.
        /// </summary>
        public static string AuthorContent {
            get {
                return ResourceManager.GetString("AuthorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        public static string AuthorTitle {
            get {
                return ResourceManager.GetString("AuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://weibo.cn/xepher.
        /// </summary>
        public static string AuthorWeiboContent {
            get {
                return ResourceManager.GetString("AuthorWeiboContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weibo.
        /// </summary>
        public static string AuthorWeiboTitle {
            get {
                return ResourceManager.GetString("AuthorWeiboTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击加载最新公告.
        /// </summary>
        public static string BtnLoadTrafficInfo {
            get {
                return ResourceManager.GetString("BtnLoadTrafficInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车辆：.
        /// </summary>
        public static string BusBusID {
            get {
                return ResourceManager.GetString("BusBusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前位置：.
        /// </summary>
        public static string BusStation {
            get {
                return ResourceManager.GetString("BusStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 到达时间：.
        /// </summary>
        public static string BusTime {
            get {
                return ResourceManager.GetString("BusTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 距离：.
        /// </summary>
        public static string BusTTL {
            get {
                return ResourceManager.GetString("BusTTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2012-2013 All Rights Reserved..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无锡公交,锡惠公交.
        /// </summary>
        public static string DataSourceContent {
            get {
                return ResourceManager.GetString("DataSourceContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据来源.
        /// </summary>
        public static string DataSourceTitle {
            get {
                return ResourceManager.GetString("DataSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xepher@126.com.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下拉刷新.
        /// </summary>
        public static string ExtendListBoxPullingDown {
            get {
                return ResourceManager.GetString("ExtendListBoxPullingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 松开刷新.
        /// </summary>
        public static string ExtendListBoxPullingDownReadyToRelease {
            get {
                return ResourceManager.GetString("ExtendListBoxPullingDownReadyToRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上拉加载更多.
        /// </summary>
        public static string ExtendListBoxPullingUp {
            get {
                return ResourceManager.GetString("ExtendListBoxPullingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 松开加载更多.
        /// </summary>
        public static string ExtendListBoxPullingUpReadyToRelease {
            get {
                return ResourceManager.GetString("ExtendListBoxPullingUpReadyToRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库损毁，尝试修复... {0}/3.
        /// </summary>
        public static string LoadingTextDBDestroyed {
            get {
                return ResourceManager.GetString("LoadingTextDBDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载线路信息....
        /// </summary>
        public static string LoadingTextPrepareLines {
            get {
                return ResourceManager.GetString("LoadingTextPrepareLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 释放数据库....
        /// </summary>
        public static string LoadingTextReleaseDB {
            get {
                return ResourceManager.GetString("LoadingTextReleaseDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定到“开始”屏幕.
        /// </summary>
        public static string MenuPinToStart {
            get {
                return ResourceManager.GetString("MenuPinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定退出程序吗？.
        /// </summary>
        public static string MsgExitApplication {
            get {
                return ResourceManager.GetString("MsgExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS服务未打开！.
        /// </summary>
        public static string MsgGPSServiceNotOpen {
            get {
                return ResourceManager.GetString("MsgGPSServiceNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无网络连接！请确认网络连接！.
        /// </summary>
        public static string MsgNetworkUnavailable {
            get {
                return ResourceManager.GetString("MsgNetworkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无此线路信息！.
        /// </summary>
        public static string MsgNoLine {
            get {
                return ResourceManager.GetString("MsgNoLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有更多线路了.
        /// </summary>
        public static string MsgNoMoreLines {
            get {
                return ResourceManager.GetString("MsgNoMoreLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将 {0} 固定到“开始”屏幕吗？.
        /// </summary>
        public static string MsgPinToStart {
            get {
                return ResourceManager.GetString("MsgPinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 短信查询由运营商收取通讯费，接收免费。.
        /// </summary>
        public static string MsgSendSMS {
            get {
                return ResourceManager.GetString("MsgSendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 车辆.
        /// </summary>
        public static string PageBus {
            get {
                return ResourceManager.GetString("PageBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线路.
        /// </summary>
        public static string PageLine {
            get {
                return ResourceManager.GetString("PageLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定位.
        /// </summary>
        public static string PageLocate {
            get {
                return ResourceManager.GetString("PageLocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        public static string PageOther {
            get {
                return ResourceManager.GetString("PageOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查询.
        /// </summary>
        public static string PageSearch {
            get {
                return ResourceManager.GetString("PageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线路查询.
        /// </summary>
        public static string PageSearchTitleLineSearch {
            get {
                return ResourceManager.GetString("PageSearchTitleLineSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 站台查询.
        /// </summary>
        public static string PageSearchTitleStationSearch {
            get {
                return ResourceManager.GetString("PageSearchTitleStationSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 站台.
        /// </summary>
        public static string PageStations {
            get {
                return ResourceManager.GetString("PageStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公告.
        /// </summary>
        public static string PageTrafficInfo {
            get {
                return ResourceManager.GetString("PageTrafficInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 线路:.
        /// </summary>
        public static string PopupLineText {
            get {
                return ResourceManager.GetString("PopupLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载中....
        /// </summary>
        public static string PopupLoadingText {
            get {
                return ResourceManager.GetString("PopupLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 点击检查更新.
        /// </summary>
        public static string SettingsBtnUpdate {
            get {
                return ResourceManager.GetString("SettingsBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题：.
        /// </summary>
        public static string SettingsTxtTheme {
            get {
                return ResourceManager.GetString("SettingsTxtTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库更新：.
        /// </summary>
        public static string SettingsTxtUpdate {
            get {
                return ResourceManager.GetString("SettingsTxtUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库已是最新版！.
        /// </summary>
        public static string SettingsUpdateAlreadyLatest {
            get {
                return ResourceManager.GetString("SettingsUpdateAlreadyLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新出错，数据库已回滚！.
        /// </summary>
        public static string SettingsUpdateFailured {
            get {
                return ResourceManager.GetString("SettingsUpdateFailured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取更新信息失败！.
        /// </summary>
        public static string SettingsUpdateFetchInfoError {
            get {
                return ResourceManager.GetString("SettingsUpdateFetchInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新成功！.
        /// </summary>
        public static string SettingsUpdateSuccessed {
            get {
                return ResourceManager.GetString("SettingsUpdateSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: 更新信息来自无锡公交官网，若不包含数据库更新，请忽略。.
        /// </summary>
        public static string SettingsUpdateTip {
            get {
                return ResourceManager.GetString("SettingsUpdateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知错误！.
        /// </summary>
        public static string SettingsUpdateUnknownError {
            get {
                return ResourceManager.GetString("SettingsUpdateUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载中....
        /// </summary>
        public static string SystemTrayLoadingText {
            get {
                return ResourceManager.GetString("SystemTrayLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出程序.
        /// </summary>
        public static string TitleExitApplication {
            get {
                return ResourceManager.GetString("TitleExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 固定到“开始”屏幕.
        /// </summary>
        public static string TitlePinToStart {
            get {
                return ResourceManager.GetString("TitlePinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发送短信.
        /// </summary>
        public static string TitleSendSMS {
            get {
                return ResourceManager.GetString("TitleSendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新说明.
        /// </summary>
        public static string UpdateInformation {
            get {
                return ResourceManager.GetString("UpdateInformation", resourceCulture);
            }
        }
    }
}
