//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace org.xepher.webservice.BusTravelGuideServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BusTravelGuideServiceReference.BusTravelGuideSoap")]
    public interface BusTravelGuideSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getBusALStationInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetBusALStationInfo(string routeid, string segmentID, string dualserialIDs, System.AsyncCallback callback, object asyncState);
        
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetBusALStationInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getBusALStationInfo2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetBusALStationInfo2(string subrouteName, string statinoNo, string telphone, System.AsyncCallback callback, object asyncState);
        
        string EndgetBusALStationInfo2(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getQDBusALStationInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetQDBusALStationInfo(string routeid, string segmentid, string stationseq, System.AsyncCallback callback, object asyncState);
        
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetQDBusALStationInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getBusALStationInfoCommon", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetBusALStationInfoCommon(string routeid, string segmentid, string stationseq, ref string fdisMsg, System.AsyncCallback callback, object asyncState);
        
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetBusALStationInfoCommon(ref string fdisMsg, System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getRouteInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetRouteInfo(System.AsyncCallback callback, object asyncState);
        
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetRouteInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getSegmentInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetSegmentInfo(string routeid, System.AsyncCallback callback, object asyncState);
        
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetSegmentInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getStationInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetStationInfo(string stationid, string stationname, System.AsyncCallback callback, object asyncState);
        
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetStationInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/getSegmentStationInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BegingetSegmentStationInfo(string routeid, string segmentid, System.AsyncCallback callback, object asyncState);
        
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetSegmentStationInfo(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BusTravelGuideSoapChannel : org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getBusALStationInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getBusALStationInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getBusALStationInfo2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getBusALStationInfo2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getQDBusALStationInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getQDBusALStationInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getBusALStationInfoCommonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getBusALStationInfoCommonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string fdisMsg {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getRouteInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getRouteInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getSegmentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getSegmentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getStationInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getStationInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getSegmentStationInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getSegmentStationInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BusTravelGuideSoapClient : System.ServiceModel.ClientBase<org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap>, org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap {
        
        private BeginOperationDelegate onBegingetBusALStationInfoDelegate;
        
        private EndOperationDelegate onEndgetBusALStationInfoDelegate;
        
        private System.Threading.SendOrPostCallback ongetBusALStationInfoCompletedDelegate;
        
        private BeginOperationDelegate onBegingetBusALStationInfo2Delegate;
        
        private EndOperationDelegate onEndgetBusALStationInfo2Delegate;
        
        private System.Threading.SendOrPostCallback ongetBusALStationInfo2CompletedDelegate;
        
        private BeginOperationDelegate onBegingetQDBusALStationInfoDelegate;
        
        private EndOperationDelegate onEndgetQDBusALStationInfoDelegate;
        
        private System.Threading.SendOrPostCallback ongetQDBusALStationInfoCompletedDelegate;
        
        private BeginOperationDelegate onBegingetBusALStationInfoCommonDelegate;
        
        private EndOperationDelegate onEndgetBusALStationInfoCommonDelegate;
        
        private System.Threading.SendOrPostCallback ongetBusALStationInfoCommonCompletedDelegate;
        
        private BeginOperationDelegate onBegingetRouteInfoDelegate;
        
        private EndOperationDelegate onEndgetRouteInfoDelegate;
        
        private System.Threading.SendOrPostCallback ongetRouteInfoCompletedDelegate;
        
        private BeginOperationDelegate onBegingetSegmentInfoDelegate;
        
        private EndOperationDelegate onEndgetSegmentInfoDelegate;
        
        private System.Threading.SendOrPostCallback ongetSegmentInfoCompletedDelegate;
        
        private BeginOperationDelegate onBegingetStationInfoDelegate;
        
        private EndOperationDelegate onEndgetStationInfoDelegate;
        
        private System.Threading.SendOrPostCallback ongetStationInfoCompletedDelegate;
        
        private BeginOperationDelegate onBegingetSegmentStationInfoDelegate;
        
        private EndOperationDelegate onEndgetSegmentStationInfoDelegate;
        
        private System.Threading.SendOrPostCallback ongetSegmentStationInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public BusTravelGuideSoapClient() {
        }
        
        public BusTravelGuideSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BusTravelGuideSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusTravelGuideSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BusTravelGuideSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<getBusALStationInfoCompletedEventArgs> getBusALStationInfoCompleted;
        
        public event System.EventHandler<getBusALStationInfo2CompletedEventArgs> getBusALStationInfo2Completed;
        
        public event System.EventHandler<getQDBusALStationInfoCompletedEventArgs> getQDBusALStationInfoCompleted;
        
        public event System.EventHandler<getBusALStationInfoCommonCompletedEventArgs> getBusALStationInfoCommonCompleted;
        
        public event System.EventHandler<getRouteInfoCompletedEventArgs> getRouteInfoCompleted;
        
        public event System.EventHandler<getSegmentInfoCompletedEventArgs> getSegmentInfoCompleted;
        
        public event System.EventHandler<getStationInfoCompletedEventArgs> getStationInfoCompleted;
        
        public event System.EventHandler<getSegmentStationInfoCompletedEventArgs> getSegmentStationInfoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.BegingetBusALStationInfo(string routeid, string segmentID, string dualserialIDs, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetBusALStationInfo(routeid, segmentID, dualserialIDs, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.EndgetBusALStationInfo(System.IAsyncResult result) {
            return base.Channel.EndgetBusALStationInfo(result);
        }
        
        private System.IAsyncResult OnBegingetBusALStationInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string routeid = ((string)(inValues[0]));
            string segmentID = ((string)(inValues[1]));
            string dualserialIDs = ((string)(inValues[2]));
            return ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).BegingetBusALStationInfo(routeid, segmentID, dualserialIDs, callback, asyncState);
        }
        
        private object[] OnEndgetBusALStationInfo(System.IAsyncResult result) {
            org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement retVal = ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).EndgetBusALStationInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetBusALStationInfoCompleted(object state) {
            if ((this.getBusALStationInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getBusALStationInfoCompleted(this, new getBusALStationInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getBusALStationInfoAsync(string routeid, string segmentID, string dualserialIDs) {
            this.getBusALStationInfoAsync(routeid, segmentID, dualserialIDs, null);
        }
        
        public void getBusALStationInfoAsync(string routeid, string segmentID, string dualserialIDs, object userState) {
            if ((this.onBegingetBusALStationInfoDelegate == null)) {
                this.onBegingetBusALStationInfoDelegate = new BeginOperationDelegate(this.OnBegingetBusALStationInfo);
            }
            if ((this.onEndgetBusALStationInfoDelegate == null)) {
                this.onEndgetBusALStationInfoDelegate = new EndOperationDelegate(this.OnEndgetBusALStationInfo);
            }
            if ((this.ongetBusALStationInfoCompletedDelegate == null)) {
                this.ongetBusALStationInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetBusALStationInfoCompleted);
            }
            base.InvokeAsync(this.onBegingetBusALStationInfoDelegate, new object[] {
                        routeid,
                        segmentID,
                        dualserialIDs}, this.onEndgetBusALStationInfoDelegate, this.ongetBusALStationInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.BegingetBusALStationInfo2(string subrouteName, string statinoNo, string telphone, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetBusALStationInfo2(subrouteName, statinoNo, telphone, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.EndgetBusALStationInfo2(System.IAsyncResult result) {
            return base.Channel.EndgetBusALStationInfo2(result);
        }
        
        private System.IAsyncResult OnBegingetBusALStationInfo2(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string subrouteName = ((string)(inValues[0]));
            string statinoNo = ((string)(inValues[1]));
            string telphone = ((string)(inValues[2]));
            return ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).BegingetBusALStationInfo2(subrouteName, statinoNo, telphone, callback, asyncState);
        }
        
        private object[] OnEndgetBusALStationInfo2(System.IAsyncResult result) {
            string retVal = ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).EndgetBusALStationInfo2(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetBusALStationInfo2Completed(object state) {
            if ((this.getBusALStationInfo2Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getBusALStationInfo2Completed(this, new getBusALStationInfo2CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getBusALStationInfo2Async(string subrouteName, string statinoNo, string telphone) {
            this.getBusALStationInfo2Async(subrouteName, statinoNo, telphone, null);
        }
        
        public void getBusALStationInfo2Async(string subrouteName, string statinoNo, string telphone, object userState) {
            if ((this.onBegingetBusALStationInfo2Delegate == null)) {
                this.onBegingetBusALStationInfo2Delegate = new BeginOperationDelegate(this.OnBegingetBusALStationInfo2);
            }
            if ((this.onEndgetBusALStationInfo2Delegate == null)) {
                this.onEndgetBusALStationInfo2Delegate = new EndOperationDelegate(this.OnEndgetBusALStationInfo2);
            }
            if ((this.ongetBusALStationInfo2CompletedDelegate == null)) {
                this.ongetBusALStationInfo2CompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetBusALStationInfo2Completed);
            }
            base.InvokeAsync(this.onBegingetBusALStationInfo2Delegate, new object[] {
                        subrouteName,
                        statinoNo,
                        telphone}, this.onEndgetBusALStationInfo2Delegate, this.ongetBusALStationInfo2CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.BegingetQDBusALStationInfo(string routeid, string segmentid, string stationseq, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetQDBusALStationInfo(routeid, segmentid, stationseq, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.EndgetQDBusALStationInfo(System.IAsyncResult result) {
            return base.Channel.EndgetQDBusALStationInfo(result);
        }
        
        private System.IAsyncResult OnBegingetQDBusALStationInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string routeid = ((string)(inValues[0]));
            string segmentid = ((string)(inValues[1]));
            string stationseq = ((string)(inValues[2]));
            return ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).BegingetQDBusALStationInfo(routeid, segmentid, stationseq, callback, asyncState);
        }
        
        private object[] OnEndgetQDBusALStationInfo(System.IAsyncResult result) {
            org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement retVal = ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).EndgetQDBusALStationInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetQDBusALStationInfoCompleted(object state) {
            if ((this.getQDBusALStationInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getQDBusALStationInfoCompleted(this, new getQDBusALStationInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getQDBusALStationInfoAsync(string routeid, string segmentid, string stationseq) {
            this.getQDBusALStationInfoAsync(routeid, segmentid, stationseq, null);
        }
        
        public void getQDBusALStationInfoAsync(string routeid, string segmentid, string stationseq, object userState) {
            if ((this.onBegingetQDBusALStationInfoDelegate == null)) {
                this.onBegingetQDBusALStationInfoDelegate = new BeginOperationDelegate(this.OnBegingetQDBusALStationInfo);
            }
            if ((this.onEndgetQDBusALStationInfoDelegate == null)) {
                this.onEndgetQDBusALStationInfoDelegate = new EndOperationDelegate(this.OnEndgetQDBusALStationInfo);
            }
            if ((this.ongetQDBusALStationInfoCompletedDelegate == null)) {
                this.ongetQDBusALStationInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetQDBusALStationInfoCompleted);
            }
            base.InvokeAsync(this.onBegingetQDBusALStationInfoDelegate, new object[] {
                        routeid,
                        segmentid,
                        stationseq}, this.onEndgetQDBusALStationInfoDelegate, this.ongetQDBusALStationInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.BegingetBusALStationInfoCommon(string routeid, string segmentid, string stationseq, ref string fdisMsg, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetBusALStationInfoCommon(routeid, segmentid, stationseq, ref fdisMsg, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.EndgetBusALStationInfoCommon(ref string fdisMsg, System.IAsyncResult result) {
            return base.Channel.EndgetBusALStationInfoCommon(ref fdisMsg, result);
        }
        
        private System.IAsyncResult OnBegingetBusALStationInfoCommon(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string routeid = ((string)(inValues[0]));
            string segmentid = ((string)(inValues[1]));
            string stationseq = ((string)(inValues[2]));
            string fdisMsg = ((string)(inValues[3]));
            return ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).BegingetBusALStationInfoCommon(routeid, segmentid, stationseq, ref fdisMsg, callback, asyncState);
        }
        
        private object[] OnEndgetBusALStationInfoCommon(System.IAsyncResult result) {
            string fdisMsg = this.GetDefaultValueForInitialization<string>();
            org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement retVal = ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).EndgetBusALStationInfoCommon(ref fdisMsg, result);
            return new object[] {
                    fdisMsg,
                    retVal};
        }
        
        private void OngetBusALStationInfoCommonCompleted(object state) {
            if ((this.getBusALStationInfoCommonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getBusALStationInfoCommonCompleted(this, new getBusALStationInfoCommonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getBusALStationInfoCommonAsync(string routeid, string segmentid, string stationseq, string fdisMsg) {
            this.getBusALStationInfoCommonAsync(routeid, segmentid, stationseq, fdisMsg, null);
        }
        
        public void getBusALStationInfoCommonAsync(string routeid, string segmentid, string stationseq, string fdisMsg, object userState) {
            if ((this.onBegingetBusALStationInfoCommonDelegate == null)) {
                this.onBegingetBusALStationInfoCommonDelegate = new BeginOperationDelegate(this.OnBegingetBusALStationInfoCommon);
            }
            if ((this.onEndgetBusALStationInfoCommonDelegate == null)) {
                this.onEndgetBusALStationInfoCommonDelegate = new EndOperationDelegate(this.OnEndgetBusALStationInfoCommon);
            }
            if ((this.ongetBusALStationInfoCommonCompletedDelegate == null)) {
                this.ongetBusALStationInfoCommonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetBusALStationInfoCommonCompleted);
            }
            base.InvokeAsync(this.onBegingetBusALStationInfoCommonDelegate, new object[] {
                        routeid,
                        segmentid,
                        stationseq,
                        fdisMsg}, this.onEndgetBusALStationInfoCommonDelegate, this.ongetBusALStationInfoCommonCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.BegingetRouteInfo(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetRouteInfo(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.EndgetRouteInfo(System.IAsyncResult result) {
            return base.Channel.EndgetRouteInfo(result);
        }
        
        private System.IAsyncResult OnBegingetRouteInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).BegingetRouteInfo(callback, asyncState);
        }
        
        private object[] OnEndgetRouteInfo(System.IAsyncResult result) {
            org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement retVal = ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).EndgetRouteInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetRouteInfoCompleted(object state) {
            if ((this.getRouteInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getRouteInfoCompleted(this, new getRouteInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getRouteInfoAsync() {
            this.getRouteInfoAsync(null);
        }
        
        public void getRouteInfoAsync(object userState) {
            if ((this.onBegingetRouteInfoDelegate == null)) {
                this.onBegingetRouteInfoDelegate = new BeginOperationDelegate(this.OnBegingetRouteInfo);
            }
            if ((this.onEndgetRouteInfoDelegate == null)) {
                this.onEndgetRouteInfoDelegate = new EndOperationDelegate(this.OnEndgetRouteInfo);
            }
            if ((this.ongetRouteInfoCompletedDelegate == null)) {
                this.ongetRouteInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetRouteInfoCompleted);
            }
            base.InvokeAsync(this.onBegingetRouteInfoDelegate, null, this.onEndgetRouteInfoDelegate, this.ongetRouteInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.BegingetSegmentInfo(string routeid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetSegmentInfo(routeid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.EndgetSegmentInfo(System.IAsyncResult result) {
            return base.Channel.EndgetSegmentInfo(result);
        }
        
        private System.IAsyncResult OnBegingetSegmentInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string routeid = ((string)(inValues[0]));
            return ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).BegingetSegmentInfo(routeid, callback, asyncState);
        }
        
        private object[] OnEndgetSegmentInfo(System.IAsyncResult result) {
            org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement retVal = ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).EndgetSegmentInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetSegmentInfoCompleted(object state) {
            if ((this.getSegmentInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getSegmentInfoCompleted(this, new getSegmentInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getSegmentInfoAsync(string routeid) {
            this.getSegmentInfoAsync(routeid, null);
        }
        
        public void getSegmentInfoAsync(string routeid, object userState) {
            if ((this.onBegingetSegmentInfoDelegate == null)) {
                this.onBegingetSegmentInfoDelegate = new BeginOperationDelegate(this.OnBegingetSegmentInfo);
            }
            if ((this.onEndgetSegmentInfoDelegate == null)) {
                this.onEndgetSegmentInfoDelegate = new EndOperationDelegate(this.OnEndgetSegmentInfo);
            }
            if ((this.ongetSegmentInfoCompletedDelegate == null)) {
                this.ongetSegmentInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetSegmentInfoCompleted);
            }
            base.InvokeAsync(this.onBegingetSegmentInfoDelegate, new object[] {
                        routeid}, this.onEndgetSegmentInfoDelegate, this.ongetSegmentInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.BegingetStationInfo(string stationid, string stationname, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetStationInfo(stationid, stationname, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.EndgetStationInfo(System.IAsyncResult result) {
            return base.Channel.EndgetStationInfo(result);
        }
        
        private System.IAsyncResult OnBegingetStationInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string stationid = ((string)(inValues[0]));
            string stationname = ((string)(inValues[1]));
            return ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).BegingetStationInfo(stationid, stationname, callback, asyncState);
        }
        
        private object[] OnEndgetStationInfo(System.IAsyncResult result) {
            org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement retVal = ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).EndgetStationInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetStationInfoCompleted(object state) {
            if ((this.getStationInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getStationInfoCompleted(this, new getStationInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getStationInfoAsync(string stationid, string stationname) {
            this.getStationInfoAsync(stationid, stationname, null);
        }
        
        public void getStationInfoAsync(string stationid, string stationname, object userState) {
            if ((this.onBegingetStationInfoDelegate == null)) {
                this.onBegingetStationInfoDelegate = new BeginOperationDelegate(this.OnBegingetStationInfo);
            }
            if ((this.onEndgetStationInfoDelegate == null)) {
                this.onEndgetStationInfoDelegate = new EndOperationDelegate(this.OnEndgetStationInfo);
            }
            if ((this.ongetStationInfoCompletedDelegate == null)) {
                this.ongetStationInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetStationInfoCompleted);
            }
            base.InvokeAsync(this.onBegingetStationInfoDelegate, new object[] {
                        stationid,
                        stationname}, this.onEndgetStationInfoDelegate, this.ongetStationInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.BegingetSegmentStationInfo(string routeid, string segmentid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetSegmentStationInfo(routeid, segmentid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap.EndgetSegmentStationInfo(System.IAsyncResult result) {
            return base.Channel.EndgetSegmentStationInfo(result);
        }
        
        private System.IAsyncResult OnBegingetSegmentStationInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string routeid = ((string)(inValues[0]));
            string segmentid = ((string)(inValues[1]));
            return ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).BegingetSegmentStationInfo(routeid, segmentid, callback, asyncState);
        }
        
        private object[] OnEndgetSegmentStationInfo(System.IAsyncResult result) {
            org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement retVal = ((org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap)(this)).EndgetSegmentStationInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetSegmentStationInfoCompleted(object state) {
            if ((this.getSegmentStationInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getSegmentStationInfoCompleted(this, new getSegmentStationInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getSegmentStationInfoAsync(string routeid, string segmentid) {
            this.getSegmentStationInfoAsync(routeid, segmentid, null);
        }
        
        public void getSegmentStationInfoAsync(string routeid, string segmentid, object userState) {
            if ((this.onBegingetSegmentStationInfoDelegate == null)) {
                this.onBegingetSegmentStationInfoDelegate = new BeginOperationDelegate(this.OnBegingetSegmentStationInfo);
            }
            if ((this.onEndgetSegmentStationInfoDelegate == null)) {
                this.onEndgetSegmentStationInfoDelegate = new EndOperationDelegate(this.OnEndgetSegmentStationInfo);
            }
            if ((this.ongetSegmentStationInfoCompletedDelegate == null)) {
                this.ongetSegmentStationInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetSegmentStationInfoCompleted);
            }
            base.InvokeAsync(this.onBegingetSegmentStationInfoDelegate, new object[] {
                        routeid,
                        segmentid}, this.onEndgetSegmentStationInfoDelegate, this.ongetSegmentStationInfoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap CreateChannel() {
            return new BusTravelGuideSoapClientChannel(this);
        }
        
        private class BusTravelGuideSoapClientChannel : ChannelBase<org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap>, org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap {
            
            public BusTravelGuideSoapClientChannel(System.ServiceModel.ClientBase<org.xepher.webservice.BusTravelGuideServiceReference.BusTravelGuideSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BegingetBusALStationInfo(string routeid, string segmentID, string dualserialIDs, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = routeid;
                _args[1] = segmentID;
                _args[2] = dualserialIDs;
                System.IAsyncResult _result = base.BeginInvoke("getBusALStationInfo", _args, callback, asyncState);
                return _result;
            }
            
            public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetBusALStationInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement _result = ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(base.EndInvoke("getBusALStationInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetBusALStationInfo2(string subrouteName, string statinoNo, string telphone, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = subrouteName;
                _args[1] = statinoNo;
                _args[2] = telphone;
                System.IAsyncResult _result = base.BeginInvoke("getBusALStationInfo2", _args, callback, asyncState);
                return _result;
            }
            
            public string EndgetBusALStationInfo2(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("getBusALStationInfo2", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetQDBusALStationInfo(string routeid, string segmentid, string stationseq, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = routeid;
                _args[1] = segmentid;
                _args[2] = stationseq;
                System.IAsyncResult _result = base.BeginInvoke("getQDBusALStationInfo", _args, callback, asyncState);
                return _result;
            }
            
            public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetQDBusALStationInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement _result = ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(base.EndInvoke("getQDBusALStationInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetBusALStationInfoCommon(string routeid, string segmentid, string stationseq, ref string fdisMsg, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = routeid;
                _args[1] = segmentid;
                _args[2] = stationseq;
                _args[3] = fdisMsg;
                System.IAsyncResult _result = base.BeginInvoke("getBusALStationInfoCommon", _args, callback, asyncState);
                fdisMsg = ((string)(_args[3]));
                return _result;
            }
            
            public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetBusALStationInfoCommon(ref string fdisMsg, System.IAsyncResult result) {
                object[] _args = new object[1];
                _args[0] = fdisMsg;
                org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement _result = ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(base.EndInvoke("getBusALStationInfoCommon", _args, result)));
                fdisMsg = ((string)(_args[0]));
                return _result;
            }
            
            public System.IAsyncResult BegingetRouteInfo(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getRouteInfo", _args, callback, asyncState);
                return _result;
            }
            
            public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetRouteInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement _result = ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(base.EndInvoke("getRouteInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetSegmentInfo(string routeid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = routeid;
                System.IAsyncResult _result = base.BeginInvoke("getSegmentInfo", _args, callback, asyncState);
                return _result;
            }
            
            public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetSegmentInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement _result = ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(base.EndInvoke("getSegmentInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetStationInfo(string stationid, string stationname, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = stationid;
                _args[1] = stationname;
                System.IAsyncResult _result = base.BeginInvoke("getStationInfo", _args, callback, asyncState);
                return _result;
            }
            
            public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetStationInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement _result = ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(base.EndInvoke("getStationInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetSegmentStationInfo(string routeid, string segmentid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = routeid;
                _args[1] = segmentid;
                System.IAsyncResult _result = base.BeginInvoke("getSegmentStationInfo", _args, callback, asyncState);
                return _result;
            }
            
            public org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement EndgetSegmentStationInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement _result = ((org.xepher.webservice.BusTravelGuideServiceReference.ArrayOfXElement)(base.EndInvoke("getSegmentStationInfo", _args, result)));
                return _result;
            }
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Silverlight.Phone.ServiceReference", "3.7.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement() {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes {
            get {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema() {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            ) {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            ) {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element)) {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else {
                    reader.Skip();
                }
            }
        }
    }
}
